import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the node folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  blogSidebar: [{ type: 'autogenerated', dirName: './blog' }],

  // But you can create a sidebar manually

  // blogSidebar: [
  //   "intro",
  //   "hello",
  //   {
  //     type: "category",
  //     label: "node-nest-1.mdx",
  //     items: ["blog-nodejs-1", "blog-nodejs-2"],
  //   },
  // ],
};

export default sidebars;
