import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the node folder structure
  nodeSidebar: [{ type: 'autogenerated', dirName: '.' }],
  // reactSidebar: [{ type: 'autogenerated', dirName: './react' }],
  // blogSidebar: [{ type: 'autogenerated', dirName: './develop' }],

  // But you can create a sidebar manually

  // blogSidebar: [
  //   "intro",
  //   "hello",
  //   {
  //     type: "category",
  //     label: "node-nest-1.mdx",
  //     items: ["develop-develop-1", "develop-develop-2"],
  //   },
  // ],
};

export default sidebars;
